### ISSUE TITLE
Possible to use UIElements?

### ISSUE THREAD

**Issue by MostHated** [DaCookie/multiple-editors#2]
Hey there,
    I just started checking out this asset, it looks quite interesting. I was wondering if it supports drawing with UIElements?

Thanks,
-MH

**Comment by hubertgdev** [comment]
I think so, yeah, since the editor drawing is up to you :)

**Comment by MostHated** [comment]
I had attempted to give it a go. I see that ```OnInspectorGui()``` is implemented, but it looks like ```VisualElement CreateInspectorGUI()``` callback might not be implemented that is needed for inspector drawing?

**Comment by hubertgdev** [comment]
Ok my bad, I didn't know there was a specific callback method to implement. I don't have the time right now, but I'll check it out very soon this week ;)

**Comment by MostHated** [comment]
Sure thing, no worries. 👍

**Comment by hubertgdev** [comment]
Sorry, I found another bug that I wanted to fix before adding new features, including visual elements support. Mostly because it's related to the functionnality I used the most: GameObject custom editors.

Unity acts really weird when you put a `[CusomEditor(typeof(GameObject))]` somewhere. [I've started a thread on Unity forurms that exposes the issue](https://forum.unity.com/threads/gameobject-custom-editor-prevents-drawing-3d-models-preview.997988/) some days ago, because I can't find a solution since I saw it last week.
Sorry again for not keeping my promise! :p

**Comment by MostHated** [comment]
Sorry for the late reply, I somehow missed that you had. Not sure if this is a route you care to go, but I found it worked out well for me to use one default editor using:

```cs
[CanEditMultipleObjects]
[CustomEditor(typeof(Object), true, isFallback = true)]
```

Then from there, I use things similar to the following (I was doing fields, but of course you can take whatever course you need at that point):

<details>
<summary>Objects</summary>


```cs
case { } a when a.FieldType == typeof(Object):
case { } b when typeof(Object).IsSubclassOf(b.FieldType):
case { } c when typeof(Object).IsAssignableFrom(c.FieldType):
```

</details>

<details>
<summary>Collections</summary>

```cs
case { } a when typeof(IList).IsAssignableFrom(a.FieldType):
case { } b when typeof(IList).IsSubclassOf(b.FieldType):
case { } c when typeof(ISet<>).IsAssignableFrom(c.FieldType):
case { } d when typeof(ISet<>).IsSubclassOf(d.FieldType):
```

</details>

I would imagine it might help to have a bit more control from a slightly higher level, then you can handle the GameObject however you wish? I am honestly not sure if it would make a difference with what the actual symptoms are, though. It might, though?

Thanks,
-MH

**Comment by hubertgdev** [comment]
@MostHated Hi! I finally fixed the issue with `GameObject` custom editors, so I will now check for the UIElements support. Also note that this package won't be updated, since I moved it in my *Muffin Dev for Unity* library.
You can get the updated package from :
- [the original GitLab repository](https://gitlab.com/muffin-dev/unity/standalone/multiple-editors)
- [the *Muffin Dev* GitHub fork](https://github.com/MuffnDev/multiple-editors)

I will notify you about the UIElements support here anyway :)

**Comment by MostHated** [comment]
Good deal, I did see on my "dashboard" feed thing that a new repo was made for it, so I will be sure to keep an eye on that one for the actual updates. I appreciate it. 👍

**Comment by hubertgdev** [comment]
@MostHated I pushed the version 1.2.0 of the package some minutes ago, with *UIElements* support. [The demo script](https://gitlab.com/muffin-dev/unity/standalone/multiple-editors/-/blob/master/Editor/Demos/MultipleEditorsDemo.cs) contains a usage example of a `GameObject` custom editor with *UIElement* if you want a quick preview before working with it.
I also changed the name of the namespace, which was the one before even before I publish the package on GitHub th first time. So, sorry for the inconvenience, but it's only for the best! :p

Please tell me if the tool works as you expected. It was my first experiments with *UIElements* so I could've missed something ^^

**Comment by MostHated** [comment]
Great news. I am cloning it now and will report back shortly.

**Comment by MostHated** [comment]
Awesome, you got it perfect. The example looks and works just as I had anticipated. 👍

**Comment by hubertgdev** [comment]
Great! Can you let me know about your creations with it? I'm really curious about how the tool is used :D

**Comment by MostHated** [comment]
Sure thing, will do. Though, any future correspondence, should it go through here, or should it be on GitLab? I am not too familiar with it but have no problem using it.

**Comment by hubertgdev** [comment]
@MostHated About the package, I mostly use [_GitLab_](https://gitlab.com/muffin-dev), where the original package is hosted. But I created a [fork on the MuffinDev's _GitHub_](https://github.com/MuffnDev/multiple-editors), so both are fine.
You can also find me on [_Facebook_](https://www.facebook.com/MuffinDev), [_Twitter_](https://twitter.com/MuffnDev) and _Discord_ (**HubertG#5353**) if you prefer to discuss directly instead of using issues.
Closing the issue now. See ya!
